### ISSUE TITLE
Announce: Aug 9 - Heather

### ISSUE THREAD

**Issue by bideme** [newlif/teams#26]
Announce: Aug 9 - Heather
See schedule: http://nlife.ca/teamtest/index.html

**Comment by andrewnl** [comment]
Reminder: you are scheduled to be on the announce team this Sunday
- If you are not able to do this, please reply to this email
- See schedule details: http://nlife.ca/teamtest/index.html

**Comment by artinmo** [comment]
Hi Andrew . How are you ? Just for remember about Bible School .
